// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
)

const countUnreadMentions = `-- name: CountUnreadMentions :one
SELECT COUNT(*) FROM messages m
WHERE m.room = ?1
	AND m.seq > ?2
	AND (m.from_team <> ?3 OR m.from_name <> ?4)
	AND (
		m.target_kind = 'everyone'
		OR EXISTS (
			SELECT 1 FROM message_mention mine
			WHERE mine.message_id = m.id
				AND mine.team = ?3
				AND mine.name = ?4
		)
	)
`

type CountUnreadMentionsParams struct {
	Room     string
	After    int64
	RoleTeam string
	RoleName string
}

// CountUnreadMentions is how much a role still has waiting past a position: the
// same predicate the unread cursor reads by, with no window and no filter.
func (q *Queries) CountUnreadMentions(ctx context.Context, arg CountUnreadMentionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadMentions,
		arg.Room,
		arg.After,
		arg.RoleTeam,
		arg.RoleName,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, room, seq, from_name, from_team, target_kind, text, sent_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ID         string
	Room       string
	Seq        int64
	FromName   string
	FromTeam   string
	TargetKind string
	Text       string
	SentAt     string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.Room,
		arg.Seq,
		arg.FromName,
		arg.FromTeam,
		arg.TargetKind,
		arg.Text,
		arg.SentAt,
	)
	return err
}

const insertMessageMention = `-- name: InsertMessageMention :exec
INSERT INTO message_mention (message_id, team, name) VALUES (?, ?, ?)
`

type InsertMessageMentionParams struct {
	MessageID string
	Team      string
	Name      string
}

func (q *Queries) InsertMessageMention(ctx context.Context, arg InsertMessageMentionParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageMention, arg.MessageID, arg.Team, arg.Name)
	return err
}

const mentionsInSeqRange = `-- name: MentionsInSeqRange :many
SELECT mm.message_id, mm.team, mm.name FROM message_mention mm
JOIN messages m ON m.id = mm.message_id
WHERE m.room = ?1
	AND m.seq >= ?2
	AND m.seq <= ?3
ORDER BY mm.team, mm.name
`

type MentionsInSeqRangeParams struct {
	Room    string
	FromSeq int64
	ToSeq   int64
}

// MentionsInSeqRange reads back the roles the messages of one window name, so a
// read can hand every message the target it was written with. It is bounded by
// the window's own seqs rather than by a list of ids.
func (q *Queries) MentionsInSeqRange(ctx context.Context, arg MentionsInSeqRangeParams) ([]MessageMention, error) {
	rows, err := q.db.QueryContext(ctx, mentionsInSeqRange, arg.Room, arg.FromSeq, arg.ToSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageMention
	for rows.Next() {
		var i MessageMention
		if err := rows.Scan(&i.MessageID, &i.Team, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesAsc = `-- name: MessagesAsc :many
SELECT id, seq, from_name, from_team, target_kind, text, sent_at FROM messages m
WHERE m.room = ?1
	AND m.seq > ?2
	AND (m.seq < ?3 OR ?3 = 0)
	AND (m.target_kind = ?4 OR ?4 = '')
	AND (
		EXISTS (
			SELECT 1 FROM message_mention mm
			WHERE mm.message_id = m.id
				AND mm.team = ?5
				AND mm.name = ?6
		)
		OR ?5 = ''
	)
	AND (
		(
			(m.from_team <> ?7 OR m.from_name <> ?8)
			AND (
				m.target_kind = 'everyone'
				OR EXISTS (
					SELECT 1 FROM message_mention mine
					WHERE mine.message_id = m.id
						AND mine.team = ?7
						AND mine.name = ?8
				)
			)
		)
		OR ?7 = ''
	)
ORDER BY m.seq ASC
LIMIT ?9
`

type MessagesAscParams struct {
	Room     string
	After    int64
	Before   int64
	Kind     string
	ToTeam   string
	ToName   string
	RoleTeam string
	RoleName string
	Lim      int64
}

type MessagesAscRow struct {
	ID         string
	Seq        int64
	FromName   string
	FromTeam   string
	TargetKind string
	Text       string
	SentAt     string
}

// MessagesAsc is the read window taken forward from its lower bound, which is
// how the head and unread cursors read.
//
// Every narrowing but the seq bounds is optional, switched off by the empty
// string: a team and a name are never empty, so no real role can be mistaken
// for "unfiltered". role_team and role_name switch on the unread predicate,
// which keeps what the role has not been shown: not sent by it, and either
// addressed to everyone or naming it. to_team and to_name keep only messages
// naming one particular role; several roles are read one query per role and
// merged, since the first n of the union are among the first n of one of them.
func (q *Queries) MessagesAsc(ctx context.Context, arg MessagesAscParams) ([]MessagesAscRow, error) {
	rows, err := q.db.QueryContext(ctx, messagesAsc,
		arg.Room,
		arg.After,
		arg.Before,
		arg.Kind,
		arg.ToTeam,
		arg.ToName,
		arg.RoleTeam,
		arg.RoleName,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesAscRow
	for rows.Next() {
		var i MessagesAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.FromName,
			&i.FromTeam,
			&i.TargetKind,
			&i.Text,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesDesc = `-- name: MessagesDesc :many
SELECT id, seq, from_name, from_team, target_kind, text, sent_at FROM messages m
WHERE m.room = ?1
	AND m.seq > ?2
	AND (m.seq < ?3 OR ?3 = 0)
	AND (m.target_kind = ?4 OR ?4 = '')
	AND (
		EXISTS (
			SELECT 1 FROM message_mention mm
			WHERE mm.message_id = m.id
				AND mm.team = ?5
				AND mm.name = ?6
		)
		OR ?5 = ''
	)
	AND (
		(
			(m.from_team <> ?7 OR m.from_name <> ?8)
			AND (
				m.target_kind = 'everyone'
				OR EXISTS (
					SELECT 1 FROM message_mention mine
					WHERE mine.message_id = m.id
						AND mine.team = ?7
						AND mine.name = ?8
				)
			)
		)
		OR ?7 = ''
	)
ORDER BY m.seq DESC
LIMIT ?9
`

type MessagesDescParams struct {
	Room     string
	After    int64
	Before   int64
	Kind     string
	ToTeam   string
	ToName   string
	RoleTeam string
	RoleName string
	Lim      int64
}

type MessagesDescRow struct {
	ID         string
	Seq        int64
	FromName   string
	FromTeam   string
	TargetKind string
	Text       string
	SentAt     string
}

// MessagesDesc is MessagesAsc taken backward from its upper bound, which is how
// the tail cursor reads; the caller reverses the rows, since a read always hands
// back the conversation in the order it happened.
func (q *Queries) MessagesDesc(ctx context.Context, arg MessagesDescParams) ([]MessagesDescRow, error) {
	rows, err := q.db.QueryContext(ctx, messagesDesc,
		arg.Room,
		arg.After,
		arg.Before,
		arg.Kind,
		arg.ToTeam,
		arg.ToName,
		arg.RoleTeam,
		arg.RoleName,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesDescRow
	for rows.Next() {
		var i MessagesDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.FromName,
			&i.FromTeam,
			&i.TargetKind,
			&i.Text,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneRoomMessages = `-- name: PruneRoomMessages :exec
DELETE FROM messages WHERE room = ? AND seq <= ?
`

type PruneRoomMessagesParams struct {
	Room string
	Seq  int64
}

// PruneRoomMessages drops everything at or below a seq; the mentions of those
// messages go with them through ON DELETE CASCADE. Pruning on send keeps the
// table bounded without a background job.
func (q *Queries) PruneRoomMessages(ctx context.Context, arg PruneRoomMessagesParams) error {
	_, err := q.db.ExecContext(ctx, pruneRoomMessages, arg.Room, arg.Seq)
	return err
}
