// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Message struct {
	ID         string
	Room       string
	Seq        int64
	FromName   string
	FromTeam   string
	TargetKind string
	Text       string
	SentAt     string
}

type MessageMention struct {
	MessageID string
	Team      string
	Name      string
}

type ReadPosition struct {
	Room    string
	Team    string
	Name    string
	LastSeq int64
}

type Room struct {
	Name    string
	LastSeq int64
}
