// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Member struct {
	Token           string
	Name            string
	Team            string
	Room            string
	Kind            string
	State           string
	StateReportedAt string
}

type Message struct {
	ID        int64
	Recipient string
	FromName  string
	FromTeam  string
	FromRoom  string
	Text      string
	SentAt    string
}
