// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE token = ?
`

func (q *Queries) DeleteMember(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteMember, token)
	return err
}

const deleteMessages = `-- name: DeleteMessages :exec
DELETE FROM messages WHERE recipient = ?
`

func (q *Queries) DeleteMessages(ctx context.Context, recipient string) error {
	_, err := q.db.ExecContext(ctx, deleteMessages, recipient)
	return err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO members (token, name, team, room, kind, state, state_reported_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertMemberParams struct {
	Token           string
	Name            string
	Team            string
	Room            string
	Kind            string
	State           string
	StateReportedAt string
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertMember,
		arg.Token,
		arg.Name,
		arg.Team,
		arg.Room,
		arg.Kind,
		arg.State,
		arg.StateReportedAt,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (recipient, from_name, from_team, from_room, text, sent_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	Recipient string
	FromName  string
	FromTeam  string
	FromRoom  string
	Text      string
	SentAt    string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.Recipient,
		arg.FromName,
		arg.FromTeam,
		arg.FromRoom,
		arg.Text,
		arg.SentAt,
	)
	return err
}

const listAllMembers = `-- name: ListAllMembers :many
SELECT token, name, team, room, kind, state, state_reported_at FROM members
ORDER BY room, team, name
`

func (q *Queries) ListAllMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listAllMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.Token,
			&i.Name,
			&i.Team,
			&i.Room,
			&i.Kind,
			&i.State,
			&i.StateReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT token, name, team, room, kind, state, state_reported_at FROM members
WHERE room = ? ORDER BY team, name
`

func (q *Queries) ListRoomMembers(ctx context.Context, room string) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listRoomMembers, room)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.Token,
			&i.Name,
			&i.Team,
			&i.Room,
			&i.Kind,
			&i.State,
			&i.StateReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT token, name, team, room, kind, state, state_reported_at FROM members
WHERE room = ? AND team = ? ORDER BY name
`

type ListTeamMembersParams struct {
	Room string
	Team string
}

// Team-scoped delivery reads the team's members the same way a whole-room
// broadcast reads the room's: the recipients are whoever is in it at the
// moment the message is sent.
func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, arg.Room, arg.Team)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.Token,
			&i.Name,
			&i.Team,
			&i.Room,
			&i.Kind,
			&i.State,
			&i.StateReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberByName = `-- name: MemberByName :one
SELECT token, name, team, room, kind, state, state_reported_at FROM members
WHERE room = ? AND team = ? AND name = ?
`

type MemberByNameParams struct {
	Room string
	Team string
	Name string
}

func (q *Queries) MemberByName(ctx context.Context, arg MemberByNameParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, memberByName, arg.Room, arg.Team, arg.Name)
	var i Member
	err := row.Scan(
		&i.Token,
		&i.Name,
		&i.Team,
		&i.Room,
		&i.Kind,
		&i.State,
		&i.StateReportedAt,
	)
	return i, err
}

const memberByToken = `-- name: MemberByToken :one
SELECT token, name, team, room, kind, state, state_reported_at FROM members WHERE token = ?
`

func (q *Queries) MemberByToken(ctx context.Context, token string) (Member, error) {
	row := q.db.QueryRowContext(ctx, memberByToken, token)
	var i Member
	err := row.Scan(
		&i.Token,
		&i.Name,
		&i.Team,
		&i.Room,
		&i.Kind,
		&i.State,
		&i.StateReportedAt,
	)
	return i, err
}

const membersByRoomAndName = `-- name: MembersByRoomAndName :many
SELECT token, name, team, room, kind, state, state_reported_at FROM members
WHERE room = ? AND name = ? ORDER BY team
`

type MembersByRoomAndNameParams struct {
	Room string
	Name string
}

// Bare-name resolution falls back to this when the caller's own team has no
// such member: every other team of the room is a candidate, and two or more
// make the address ambiguous.
func (q *Queries) MembersByRoomAndName(ctx context.Context, arg MembersByRoomAndNameParams) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, membersByRoomAndName, arg.Room, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.Token,
			&i.Name,
			&i.Team,
			&i.Room,
			&i.Kind,
			&i.State,
			&i.StateReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingMessages = `-- name: PendingMessages :many
SELECT from_name, from_team, from_room, text, sent_at FROM messages
WHERE recipient = ? ORDER BY id
`

type PendingMessagesRow struct {
	FromName string
	FromTeam string
	FromRoom string
	Text     string
	SentAt   string
}

func (q *Queries) PendingMessages(ctx context.Context, recipient string) ([]PendingMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingMessages, recipient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingMessagesRow
	for rows.Next() {
		var i PendingMessagesRow
		if err := rows.Scan(
			&i.FromName,
			&i.FromTeam,
			&i.FromRoom,
			&i.Text,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemberState = `-- name: SetMemberState :execrows
UPDATE members SET state = ?, state_reported_at = ? WHERE token = ?
`

type SetMemberStateParams struct {
	State           string
	StateReportedAt string
	Token           string
}

func (q *Queries) SetMemberState(ctx context.Context, arg SetMemberStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMemberState, arg.State, arg.StateReportedAt, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setMemberTeam = `-- name: SetMemberTeam :exec
UPDATE members SET team = ? WHERE token = ?
`

type SetMemberTeamParams struct {
	Team  string
	Token string
}

func (q *Queries) SetMemberTeam(ctx context.Context, arg SetMemberTeamParams) error {
	_, err := q.db.ExecContext(ctx, setMemberTeam, arg.Team, arg.Token)
	return err
}
