// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read_positions.sql

package db

import (
	"context"
)

const advanceReadPosition = `-- name: AdvanceReadPosition :exec
UPDATE read_positions SET last_seq = ?1
WHERE room = ?2
	AND team = ?3
	AND name = ?4
	AND last_seq < ?1
`

type AdvanceReadPositionParams struct {
	LastSeq int64
	Room    string
	Team    string
	Name    string
}

// AdvanceReadPosition never moves a position backwards: reading old history
// shows what the role has already seen, and must not make newer messages unread
// again.
func (q *Queries) AdvanceReadPosition(ctx context.Context, arg AdvanceReadPositionParams) error {
	_, err := q.db.ExecContext(ctx, advanceReadPosition,
		arg.LastSeq,
		arg.Room,
		arg.Team,
		arg.Name,
	)
	return err
}

const listRoomRoles = `-- name: ListRoomRoles :many
SELECT team, name FROM read_positions WHERE room = ? ORDER BY team, name
`

type ListRoomRolesRow struct {
	Team string
	Name string
}

// ListRoomRoles lists every role of the room: everyone that has ever attended
// it. A target names one of these or it names nobody.
func (q *Queries) ListRoomRoles(ctx context.Context, room string) ([]ListRoomRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomRoles, room)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomRolesRow
	for rows.Next() {
		var i ListRoomRolesRow
		if err := rows.Scan(&i.Team, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readPosition = `-- name: ReadPosition :one
SELECT last_seq FROM read_positions WHERE room = ? AND team = ? AND name = ?
`

type ReadPositionParams struct {
	Room string
	Team string
	Name string
}

func (q *Queries) ReadPosition(ctx context.Context, arg ReadPositionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, readPosition, arg.Room, arg.Team, arg.Name)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const seedReadPosition = `-- name: SeedReadPosition :exec
INSERT INTO read_positions (room, team, name, last_seq)
SELECT r.name, ?1, ?2, r.last_seq FROM rooms r
WHERE r.name = ?3
ON CONFLICT (room, team, name) DO NOTHING
`

type SeedReadPositionParams struct {
	Team string
	Name string
	Room string
}

// SeedReadPosition creates the role's position at the room's current last_seq,
// which is what leaves a role attending for the first time with nothing unread.
// An existing position is left exactly where it is: attendance comes and goes
// with a stream, the position is the durable half of a role.
func (q *Queries) SeedReadPosition(ctx context.Context, arg SeedReadPositionParams) error {
	_, err := q.db.ExecContext(ctx, seedReadPosition, arg.Team, arg.Name, arg.Room)
	return err
}
