// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_log.sql

package db

import (
	"context"
)

const insertRoomLog = `-- name: InsertRoomLog :exec
INSERT INTO room_log (room, from_name, from_team, to_name, to_team, text, sent_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertRoomLogParams struct {
	Room     string
	FromName string
	FromTeam string
	ToName   string
	ToTeam   string
	Text     string
	SentAt   string
}

func (q *Queries) InsertRoomLog(ctx context.Context, arg InsertRoomLogParams) error {
	_, err := q.db.ExecContext(ctx, insertRoomLog,
		arg.Room,
		arg.FromName,
		arg.FromTeam,
		arg.ToName,
		arg.ToTeam,
		arg.Text,
		arg.SentAt,
	)
	return err
}

const pruneRoomLog = `-- name: PruneRoomLog :exec
DELETE FROM room_log
WHERE room_log.room = ?1
	AND room_log.id NOT IN (
		SELECT recent.id FROM room_log AS recent
		WHERE recent.room = ?1
		ORDER BY recent.id DESC LIMIT ?2
	)
`

type PruneRoomLogParams struct {
	Room string
	Keep int64
}

func (q *Queries) PruneRoomLog(ctx context.Context, arg PruneRoomLogParams) error {
	_, err := q.db.ExecContext(ctx, pruneRoomLog, arg.Room, arg.Keep)
	return err
}

const roomLogTail = `-- name: RoomLogTail :many
SELECT from_name, from_team, to_name, to_team, text, sent_at FROM room_log
WHERE room = ? ORDER BY id DESC LIMIT ?
`

type RoomLogTailParams struct {
	Room  string
	Limit int64
}

type RoomLogTailRow struct {
	FromName string
	FromTeam string
	ToName   string
	ToTeam   string
	Text     string
	SentAt   string
}

// The tail is read newest first and reversed by the caller: taking the last N
// rows the other way round would mean scanning the whole room.
func (q *Queries) RoomLogTail(ctx context.Context, arg RoomLogTailParams) ([]RoomLogTailRow, error) {
	rows, err := q.db.QueryContext(ctx, roomLogTail, arg.Room, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomLogTailRow
	for rows.Next() {
		var i RoomLogTailRow
		if err := rows.Scan(
			&i.FromName,
			&i.FromTeam,
			&i.ToName,
			&i.ToTeam,
			&i.Text,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
