// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"
)

const countRoomMessages = `-- name: CountRoomMessages :one
SELECT COUNT(*) FROM messages WHERE room = ?
`

func (q *Queries) CountRoomMessages(ctx context.Context, room string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoomMessages, room)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRoom = `-- name: DeleteRoom :execrows
DELETE FROM rooms WHERE name = ?
`

// DeleteRoom drops the counter row; the room's messages, their mentions and its
// read positions follow through ON DELETE CASCADE. No row affected means there
// was no such room.
func (q *Queries) DeleteRoom(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRoom, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureRoom = `-- name: EnsureRoom :exec
INSERT INTO rooms (name, last_seq) VALUES (?, 0) ON CONFLICT (name) DO NOTHING
`

// EnsureRoom creates the room's counter row the first time anything happens in
// it: an attend or a send, whichever comes first. That row is what makes the
// room exist, and nothing removes it but an explicit delete.
func (q *Queries) EnsureRoom(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, ensureRoom, name)
	return err
}

const listRoomNames = `-- name: ListRoomNames :many
SELECT name FROM rooms ORDER BY name
`

func (q *Queries) ListRoomNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRoomNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRoomSeq = `-- name: NextRoomSeq :one
UPDATE rooms SET last_seq = last_seq + 1 WHERE name = ? RETURNING last_seq
`

// NextRoomSeq claims the room's next seq. The counter lives in the row rather
// than being derived from MAX(seq) so that pruning the oldest messages away
// cannot hand the same seq out a second time.
func (q *Queries) NextRoomSeq(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextRoomSeq, name)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const roomLastSeq = `-- name: RoomLastSeq :one
SELECT last_seq FROM rooms WHERE name = ?
`

func (q *Queries) RoomLastSeq(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, roomLastSeq, name)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}
