// Package api anchors code generation for the crabswarm proto schema; it holds
// no Go source of its own. The go:generate directive below runs buf from this
// directory, where buf.gen.yaml lives, so `go generate ./...` reaches it: buf
// reads the schema under api/schema and emits the connect-go/gRPC Go
// bindings into api/gen and the TypeScript client types into web/src/api/gen
// (see buf.gen.yaml).
//
// The TypeScript half is generated by protoc-gen-es taken from
// web/node_modules, so `pnpm install` must have run in web/ before this.
package api

//go:generate buf generate
